### ISSUE TITLE
build scripts fail to pull down docker image

### ISSUE THREAD

**Issue by nathanielrindlaub** [aws/sagemaker-tensorflow-serving-container#175]
**Describe the bug**
Perhaps this is user error, but it seems like ```scripts/shared.sh``` fails to populate the build scripts in ```scripts/build.sh``` with the correct ```${aws_account}```, and, if you're trying to use TensorFlow >=1.13, the ```${repository}```  variable is also incorrect according to ECR container directory listed at the top of this repo's README.

**To reproduce**
Clone the repo, and attempt to build the TF v1.13 image:
```
./scripts/build.sh --version 1.13 --arch cpu
```

**Expected behavior**
When I try to build the images, I get the 'warning: ecr login failed' warning. After digging into the build scripts, it appears as though the ```get_aws_account()``` function of ```scripts/shared.sh``` is populating ```${aws_account}``` with my own AWS account ID, rather than that of the AWS account associated with a TensorFlow Serving Container image on ECR. In my case (region us-west-1) I think the ```${aws_account}``` should have been **763104351884**.

Also, ```scripts/shared.sh``` is populating the ```${repository}``` variable with **sagemaker-tensorflow-serving**, but according to this README and the AWS deep learning containers [documentation](https://github.com/aws/deep-learning-containers/blob/master/available_images.md#general-framework-containers), for TensorFlow 1.13 and above the repository should be **sagemaker-inference**.

Putting it all together, the following hard coded build script works, but the dynamically populated script fails:
```
aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 763104351884.dkr.ecr.us-west-1.amazonaws.com
docker pull 763104351884.dkr.ecr.us-west-1.amazonaws.com/tensorflow-inference:1.13.0-cpu
cp -r docker/build_artifacts/* docker/1.13/
docker build -cache-from 763104351884.dkr.ecr.us-west-1.amazonaws.com/tensorflow-inference:1.13.0-cpu --build-arg TFS_VERSION=1.13.0 --build-arg TFS_SHORT_VERSION=1.13 -f docker/1.13/Dockerfile.cpu -t tensorflow-inference:1.13.0-cpu -t tensorflow-inference:1.13-cpu  docker/1.13/
```

**System information**
A description of your system. Please provide:
- **Toolkit version**: 
- **Framework version**: 1.13
- **Python version**: 3.6
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: N

**Comment by ChuyangDeng** [comment]
Hi @nathanielrindlaub, thanks for using SageMaker!

The script you are running, `scripts/build.sh` which depends on `shared.sh`, is expected to call your own AWS account and get credentials of your own AWS account. The purpose of the scripts is for you to build the container image on your own and publish to your own ECR repo. Our production account should not be called.

This repo is used for releasing the legacy TFS container below version 1.13 and for versions under 1.13, the repository name is `sagemaker-tensorflow-serving`, that's why you see this value populated to `${repository}`. You can change it to the new repository name of `tensorflow-inference`, or you can update it with your own ECR repo name.

**Comment by nathanielrindlaub** [comment]
@ChuyangDeng thanks for your response! I don't really need to create or publish a custom container, I was just using this repo to spin up a sagemaker tensorflow serving container to mimic the production ones for local development. Sorry for the misunderstanding; I think I'm all set now.
