### ISSUE TITLE
boto3 install is missing in 1.14 image

### ISSUE THREAD

**Issue by hin7141** [aws/sagemaker-tensorflow-serving-container#181]
The 1.14 image build is missing the python package boto3. module not found.

**Comment by icywang86rui** [comment]
@hin7141 1.14 is really old now. And we don't release official images for 1.14 anymore. TF fixed a lot of security vulnerabilities in 1.15 and forward. Older versions are not recommenced. If you still want to use 1.14, you will have to patch the docker file and build it as a custom image. Hope this helps! I am resolving the issue since it's not actionable on our side. Feel free to reopen if you have any further questions.

**Comment by hin7141** [comment]
Thanks for the prompt reply! The only reason I used 1.14 is it is the latest supported version for eia according to the readme. Is it still true tho? @icywang86rui
