### ISSUE TITLE
[Question] Successfully opened dynamic library libcudnn.so.7 not show in log

### ISSUE THREAD

**Issue by Andreachen0707** [aws/sagemaker-tensorflow-serving-container#91]
Hi,
I'm working on TensorFlow serving model with GPU instance, however, the inference time is low compared to making inference locally with the same instance, i.e. deploy endpoint to ml.p2.xlarge vs locally serve on notebook instance (ml.p2.xlarge). The time difference is like 0.1s per image locally vs 0.6s per image through the endpoint.

When I check the log from cloudwatch, I can only see :
```
Successfully opened dynamic library libcuda.so.1
```
In my understanding, using cudnn should make inference faster. However, there is no sign of showing cudnn is linked. Will this be the reason why inference via endpoint on ml.p2.xlarge is slower than local inference?

Meanwhile, the model I'm using is SSD, on my personal CPU computer, the inference time is 0.05s. That means using TensorFlow serving is much slower... I don't know what could cause this issue, any help appreciated!

***Also reading from tensorflow-gpu-1.14 building [link](https://www.tensorflow.org/install/source#tested_build_configurations), should the version of cuDnn be 7.4 instead of 7.5.1.10-1 mentioned in docker-1.14?***

Best,
Andrea

**Comment by ChuyangDeng** [comment]
Hi @Andreachen0707, thank you for using SageMaker!

As regard with your first question, inference to a SageMaker endpoint is slower than inference against your local host. ("The time difference is like 0.1s per image locally vs 0.6s per image through the endpoint."): 

My understanding is that when you make inference locally, the communication is going back and forth with your localhost. However, if you deploy the endpoint to an EC2 instance, making inference means you are talking to a remote EC2 host. I believe HTTP requests/responses are faster with your localhost than with a remote host. You also mentioned you are using cudnn, which should make the inference faster; but we do not know if the improvement of speed brought by cudnn can make up the difference between localhost communication and remote host communication.

You can time it by using/not-using cudnn and make inference against your localhost; or you can do you by using/not-using cudnn and make inference against a remote endpoint. I think this will better explain the effect of cudnn.

As regard with your second question (Also reading from tensorflow-gpu-1.14 building link, should the version of cuDnn be 7.4 instead of 7.5.1.10-1 mentioned in docker-1.14?) I've forwarded the question to the team responsible for Dockerfiles and they will answer it.

Thanks

**Comment by Andreachen0707** [comment]
Hi Chuyang,
Yes, I also think the time difference is caused by sending information over air.
As for the version of cuDnn, I'm just not sure if the prebuilt tensorflow-inference docker is using cudnn since the log does not show successfully linked to cudnn. As long as the inference time is not that huge a difference, I don't think this would be an issue.

Thank you so much for your response!
